### ISSUE TITLE
Puppetforge version

### ISSUE THREAD

**Issue by nickcmaynard** [davidc/puppet_getssl#4]
Hello David,

I see your fork is further ahead that @dthielking's original repo, and that you've made some good updates.  Please could you explain the situation with the (out of date) version on Puppetforge, and yours?  Have you and Daniel come to some arrangement on maintenance of this module?

Thank you!

**Comment by davidc** [comment]
dthielking is no longer using this module so isn't able to test it or push updates to puppet forge.
I'm happy to take it over but I don't know if there's actually a way to do this, since it's in his name on puppet forge.

**Comment by nickcmaynard** [comment]
Hmm. Perhaps worth raising an issue on @dthielking's repo?

**Comment by davidc** [comment]
I have made further updates and released 1.0.0 to puppet forge:

https://forge.puppet.com/modules/davidc/getssl
